apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db-noticias
      labels:
        app: db
    spec:
      containers:
        - name: db-noticias-ct
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-noticias-cm
