apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias
spec:
  selector:
    matchLabels:
      app: sn
  serviceName: sistema-noticias
  replicas: 1
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sn
    spec:
      containers:
        - name: sistema-noticias-ct
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
              name: web
          envFrom:
            - configMapRef:
                name: sistema-noticias
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-sistema-noticias-ss
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-sistema-noticias-ss
