apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessao-sistema-noticias-ss
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
