apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistenceDisk:
    pdName: pv
  storageClassName: standard
