apiVersion: v1
kind: Pod
metadata:
  name: gke-pod
spec:
  containers:
    - name: nginx-ct
      image: nginx:latest
      volumeMounts:
        - mountPath: /pv
          name: 1st-pv
  volumes:
    - name: 1st-pv
      persistentVolumeClaim:
        claimName: gke-pvc
