apiVersion: v1
kind: Pod
metadata:
  name: gke
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /pv
          name: 1st
  volumes:
    - name: 1st
      persistentVolumeClaim:
        claimName: gke
