apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias-pod
  labels:
    app: pn
spec:
  containers:
    - name: portal-noticias-ct
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-noticias-cm
