apiVersion: v1
kind: Pod
metadata:
  name: v
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /v
          name: 1st
    - name: jenkins
      image: jenkins/jenkins:alpine
      volumeMounts:
        - mountPath: /v
          name: 1st
  volumes:
    - name: 1st
      hostPath:
        path: /Users/matt/Desktop/1st
        type: Directory
