apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: pn
    spec:
      containers:
        - name: portal-noticias-ct
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-noticias
  replicas: 3
  selector:
    matchLabels:
      app: pn
